title: MSDS Curriculum Browser
description: Various views of the MSDS Curriculum
theme: just-the-docs

url: https://trgardos.github.io/msds_curriculum_browser/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

exclude:
  - README.md
